-- ---------------------------------------------------------------------------------------
-- Insert: norpac_commons.customer_phone. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------

DROP FUNCTION IF EXISTS norpac_commons.i_customer_phone;
CREATE FUNCTION norpac_commons.i_customer_phone(
  IN p_id_customer UUID, 
  IN p_id_rt_phone_type UUID, 
  IN p_number VARCHAR, 
  IN p_extension VARCHAR, 
  IN p_is_primary BOOLEAN, 
  IN p_created_by VARCHAR
)
RETURNS norpac_commons.pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_customer_phone';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     norpac_commons.pg_val;  
  v_response     norpac_commons.pg_resp;
  v_updated_at   TIMESTAMP;
  
  -- Primary Key Field(s)
  v_id uuid := NULL;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_customer', p_id_customer, 
    'id_rt_phone_type', p_id_rt_phone_type, 
    'number', p_number, 
    'extension', p_extension, 
    'is_primary', p_is_primary, 
    'created_by', p_created_by
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------
 
  INSERT INTO norpac_commons.customer_phone (
    id_customer, 
    id_rt_phone_type, 
    number, 
    extension, 
    is_primary, 
    created_by,
    updated_by
  )
  VALUES (
    p_id_customer, 
    p_id_rt_phone_type, 
    p_number, 
    p_extension, 
    p_is_primary, 
    p_created_by,
    p_created_by
  )
  RETURNING id, updated_at INTO v_id, v_updated_at;

  v_response := (
    'OK',
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', 'A UNIQUE constraint was violated due to duplicate data'), 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the customer_phone table', 
        'Check the provided data and try again'
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', SQLERRM), 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
