-- ---------------------------------------------------------------------------------------
-- Insert: norpac_commons.pricing. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------

DROP FUNCTION IF EXISTS norpac_commons.i_pricing;
CREATE FUNCTION norpac_commons.i_pricing(
  IN p_id_product UUID, 
  IN p_id_rt_pricing_type UUID, 
  IN p_id_rt_billing_period UUID, 
  IN p_id_rt_currency_code UUID, 
  IN p_amount DECIMAL, 
  IN p_rate_per_unit DECIMAL, 
  IN p_minimum_charge DECIMAL, 
  IN p_valid_from DATE, 
  IN p_valid_to DATE, 
  IN p_metadata TEXT, 
  IN p_created_by VARCHAR
)
RETURNS norpac_commons.pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_pricing';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     norpac_commons.pg_val;  
  v_response     norpac_commons.pg_resp;
  v_updated_at   TIMESTAMP;
  
  -- Primary Key Field(s)
  v_id uuid := NULL;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_product', p_id_product, 
    'id_rt_pricing_type', p_id_rt_pricing_type, 
    'id_rt_billing_period', p_id_rt_billing_period, 
    'id_rt_currency_code', p_id_rt_currency_code, 
    'amount', p_amount, 
    'rate_per_unit', p_rate_per_unit, 
    'minimum_charge', p_minimum_charge, 
    'valid_from', p_valid_from, 
    'valid_to', p_valid_to, 
    'metadata', p_metadata, 
    'created_by', p_created_by
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------
 
  INSERT INTO norpac_commons.pricing (
    id_product, 
    id_rt_pricing_type, 
    id_rt_billing_period, 
    id_rt_currency_code, 
    amount, 
    rate_per_unit, 
    minimum_charge, 
    valid_from, 
    valid_to, 
    metadata, 
    created_by,
    updated_by
  )
  VALUES (
    p_id_product, 
    p_id_rt_pricing_type, 
    p_id_rt_billing_period, 
    p_id_rt_currency_code, 
    p_amount, 
    p_rate_per_unit, 
    p_minimum_charge, 
    p_valid_from, 
    p_valid_to, 
    p_metadata, 
    p_created_by,
    p_created_by
  )
  RETURNING id, updated_at INTO v_id, v_updated_at;

  v_response := (
    'OK',
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', 'A UNIQUE constraint was violated due to duplicate data'), 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the pricing table', 
        'Check the provided data and try again'
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', SQLERRM), 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
