-- ---------------------------------------------------------------------------------------
-- Insert: norpac_commons.product_feature_mapping. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------

DROP FUNCTION IF EXISTS norpac_commons.i_product_feature_mapping;
CREATE FUNCTION norpac_commons.i_product_feature_mapping(
  IN p_id_product UUID, 
  IN p_id_feature UUID, 
  IN p_included BOOLEAN, 
  IN p_addon_price DECIMAL, 
  IN p_metadata JSON, 
  IN p_created_by VARCHAR
)
RETURNS norpac_commons.pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_product_feature_mapping';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     norpac_commons.pg_val;  
  v_response     norpac_commons.pg_resp;
  v_updated_at   TIMESTAMP;
  
  -- Primary Key Field(s)
  v_id uuid := NULL;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_product', p_id_product, 
    'id_feature', p_id_feature, 
    'included', p_included, 
    'addon_price', p_addon_price, 
    'metadata', p_metadata, 
    'created_by', p_created_by
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------
 
  INSERT INTO norpac_commons.product_feature_mapping (
    id_product, 
    id_feature, 
    included, 
    addon_price, 
    metadata, 
    created_by,
    updated_by
  )
  VALUES (
    p_id_product, 
    p_id_feature, 
    p_included, 
    p_addon_price, 
    p_metadata, 
    p_created_by,
    p_created_by
  )
  RETURNING id, updated_at INTO v_id, v_updated_at;

  v_response := (
    'OK',
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', 'A UNIQUE constraint was violated due to duplicate data'), 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the product_feature_mapping table', 
        'Check the provided data and try again'
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', SQLERRM), 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
