-- ---------------------------------------------------------------------------------------
-- Insert: norpac_commons.schedule_rule. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------

DROP FUNCTION IF EXISTS norpac_commons.i_schedule_rule;
CREATE FUNCTION norpac_commons.i_schedule_rule(
  IN p_id_tenant UUID, 
  IN p_id_product UUID, 
  IN p_schedule_name VARCHAR, 
  IN p_start_date TIMESTAMP, 
  IN p_recurrence_rule TEXT, 
  IN p_duration_minutes INTEGER, 
  IN p_timezone VARCHAR, 
  IN p_metadata JSON, 
  IN p_created_by VARCHAR
)
RETURNS norpac_commons.pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_schedule_rule';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     norpac_commons.pg_val;  
  v_response     norpac_commons.pg_resp;
  v_updated_at   TIMESTAMP;
  
  -- Primary Key Field(s)
  v_id uuid := NULL;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_tenant', p_id_tenant, 
    'id_product', p_id_product, 
    'schedule_name', p_schedule_name, 
    'start_date', p_start_date, 
    'recurrence_rule', p_recurrence_rule, 
    'duration_minutes', p_duration_minutes, 
    'timezone', p_timezone, 
    'metadata', p_metadata, 
    'created_by', p_created_by
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------
 
  INSERT INTO norpac_commons.schedule_rule (
    id_tenant, 
    id_product, 
    schedule_name, 
    start_date, 
    recurrence_rule, 
    duration_minutes, 
    timezone, 
    metadata, 
    created_by,
    updated_by
  )
  VALUES (
    p_id_tenant, 
    p_id_product, 
    p_schedule_name, 
    p_start_date, 
    p_recurrence_rule, 
    p_duration_minutes, 
    p_timezone, 
    p_metadata, 
    p_created_by,
    p_created_by
  )
  RETURNING id, updated_at INTO v_id, v_updated_at;

  v_response := (
    'OK',
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', 'A UNIQUE constraint was violated due to duplicate data'), 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the schedule_rule table', 
        'Check the provided data and try again'
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', SQLERRM), 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
