-- ---------------------------------------------------------------------------------------
-- Insert: norpac_commons.service_order. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------

DROP FUNCTION IF EXISTS norpac_commons.i_service_order;
CREATE FUNCTION norpac_commons.i_service_order(
  IN p_id_tenant UUID, 
  IN p_id_customer UUID, 
  IN p_id_invoice UUID, 
  IN p_id_product UUID, 
  IN p_id_subscription_plan UUID, 
  IN p_id_schedule_rule UUID, 
  IN p_id_rt_service_status UUID, 
  IN p_service_date DATE, 
  IN p_metadata TEXT, 
  IN p_created_by VARCHAR
)
RETURNS norpac_commons.pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_service_order';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     norpac_commons.pg_val;  
  v_response     norpac_commons.pg_resp;
  v_updated_at   TIMESTAMP;
  
  -- Primary Key Field(s)
  v_id uuid := NULL;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_tenant', p_id_tenant, 
    'id_customer', p_id_customer, 
    'id_invoice', p_id_invoice, 
    'id_product', p_id_product, 
    'id_subscription_plan', p_id_subscription_plan, 
    'id_schedule_rule', p_id_schedule_rule, 
    'id_rt_service_status', p_id_rt_service_status, 
    'service_date', p_service_date, 
    'metadata', p_metadata, 
    'created_by', p_created_by
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------
 
  INSERT INTO norpac_commons.service_order (
    id_tenant, 
    id_customer, 
    id_invoice, 
    id_product, 
    id_subscription_plan, 
    id_schedule_rule, 
    id_rt_service_status, 
    service_date, 
    metadata, 
    created_by,
    updated_by
  )
  VALUES (
    p_id_tenant, 
    p_id_customer, 
    p_id_invoice, 
    p_id_product, 
    p_id_subscription_plan, 
    p_id_schedule_rule, 
    p_id_rt_service_status, 
    p_service_date, 
    p_metadata, 
    p_created_by,
    p_created_by
  )
  RETURNING id, updated_at INTO v_id, v_updated_at;

  v_response := (
    'OK',
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', 'A UNIQUE constraint was violated due to duplicate data'), 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the service_order table', 
        'Check the provided data and try again'
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', SQLERRM), 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
