-- ---------------------------------------------------------------------------------------
-- Insert: norpac_commons.subscription_plan. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------

DROP FUNCTION IF EXISTS norpac_commons.i_subscription_plan;
CREATE FUNCTION norpac_commons.i_subscription_plan(
  IN p_id_product UUID, 
  IN p_id_rt_billing_frequency UUID, 
  IN p_id_rt_currency_code UUID, 
  IN p_id_rt_renewal_policy UUID, 
  IN p_plan_name VARCHAR, 
  IN p_base_price DECIMAL, 
  IN p_trial_period_days INTEGER, 
  IN p_recurrence_rule TEXT, 
  IN p_metadata TEXT, 
  IN p_created_by VARCHAR
)
RETURNS norpac_commons.pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'i_subscription_plan';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     norpac_commons.pg_val;  
  v_response     norpac_commons.pg_resp;
  v_updated_at   TIMESTAMP;
  
  -- Primary Key Field(s)
  v_id uuid := NULL;

BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'id_product', p_id_product, 
    'id_rt_billing_frequency', p_id_rt_billing_frequency, 
    'id_rt_currency_code', p_id_rt_currency_code, 
    'id_rt_renewal_policy', p_id_rt_renewal_policy, 
    'plan_name', p_plan_name, 
    'base_price', p_base_price, 
    'trial_period_days', p_trial_period_days, 
    'recurrence_rule', p_recurrence_rule, 
    'metadata', p_metadata, 
    'created_by', p_created_by
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------
 
  INSERT INTO norpac_commons.subscription_plan (
    id_product, 
    id_rt_billing_frequency, 
    id_rt_currency_code, 
    id_rt_renewal_policy, 
    plan_name, 
    base_price, 
    trial_period_days, 
    recurrence_rule, 
    metadata, 
    created_by,
    updated_by
  )
  VALUES (
    p_id_product, 
    p_id_rt_billing_frequency, 
    p_id_rt_currency_code, 
    p_id_rt_renewal_policy, 
    p_plan_name, 
    p_base_price, 
    p_trial_period_days, 
    p_recurrence_rule, 
    p_metadata, 
    p_created_by,
    p_created_by
  )
  RETURNING id, updated_at INTO v_id, v_updated_at;

  v_response := (
    'OK',
    jsonb_build_object('id', v_id, 'updated_at', v_updated_at), 
    NULL, 
    '00000',
    'Insert was successful', 
    NULL, 
    NULL
  );
  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN UNIQUE_VIOLATION THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', 'A UNIQUE constraint was violated due to duplicate data'), 
        '23514', 
        'A UNIQUE constraint was violated due to duplicate data', 
        'A record already exists in the subscription_plan table', 
        'Check the provided data and try again'
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'database', 'message', SQLERRM), 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_created_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
