-- ---------------------------------------------------------------------------------------
-- Update: norpac_commons.product_service_details. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP FUNCTION IF EXISTS norpac_commons.u_product_service_details;
CREATE FUNCTION norpac_commons.u_product_service_details(
  IN p_estimated_duration_minutes INTEGER, 
  IN p_requires_pressure_wash BOOLEAN, 
  IN p_equipment_type VARCHAR, 
  IN p_base_distance_km DECIMAL, 
  IN p_metadata JSON, 
  IN p_updated_at TIMESTAMP, 
  IN p_updated_by VARCHAR
)
RETURNS norpac_commons.pg_resp
AS $$
DECLARE

  c_service_name TEXT := 'u_product_service_details';

  v_metadata     JSONB := '{}'::JSONB;
  v_errors       JSONB := '[]'::JSONB;
  v_val_resp     norpac_commons.pg_val;
  v_response     norpac_commons.pg_resp;

  v_updates      INT;
  v_message      TEXT;
  v_count        INT;
  v_updated_at   TIMESTAMP := p_updated_at;
  
  -- Primary Key Field(s)
  v_id_product uuid := p_id_product;
  
BEGIN

  -- ------------------------------------------------------
  -- Metadata
  -- ------------------------------------------------------

  v_metadata := jsonb_build_object(
    'estimated_duration_minutes', p_estimated_duration_minutes, 
    'requires_pressure_wash', p_requires_pressure_wash, 
    'equipment_type', p_equipment_type, 
    'base_distance_km', p_base_distance_km, 
    'metadata', p_metadata, 
    'updated_at', p_updated_at, 
    'updated_by', p_updated_by
  );
  
  -- ------------------------------------------------------
  -- Persist
  -- ------------------------------------------------------

  UPDATE norpac_commons.product_service_details SET
    estimated_duration_minutes = p_estimated_duration_minutes, 
    requires_pressure_wash = p_requires_pressure_wash, 
    equipment_type = p_equipment_type, 
    base_distance_km = p_base_distance_km, 
    metadata = p_metadata, 
    updated_by = p_updated_by, 
    updated_at = CURRENT_TIMESTAMP
    WHERE id_product = p_id_product
      AND DATE_TRUNC('second', updated_at) = DATE_TRUNC('second', p_updated_at)
    RETURNING id_product, updated_at INTO v_id_product, v_updated_at;
  
  GET DIAGNOSTICS v_updates = ROW_COUNT;

  IF v_updates > 0 THEN
    -- Record was updated
    v_response := (
      'OK', 
      jsonb_build_object('id_product', v_id_product, 'updated_at', v_updated_at), 
      NULL, 
      '00000',
      'Update was successful', 
      NULL, 
      NULL
  );    
  ELSE  
    -- Check for Optimistic Lock Error
    SELECT count(*) INTO v_count   
      FROM norpac_commons.product_service_details 
    WHERE id_product = v_id_product;
          
    IF (v_count > 0) THEN
      -- Record does exists but the updated_at timestamp has changed
      -- The id and updated_at values are not returned. The client must refresh the record.      
      v_message := 'The record was updated by another transaction. Refresh and try again';
      v_response := (
        'ERROR', 
        NULL, 
        jsonb_build_object('type', 'optimistic_lock', 'field', 'updated_at', 'message', v_message), 
        '00002',
        'No records were found matching the query.',
        'The UPDATED_AT query parameter does not match the current record.',
        'Obtain the latest updated_at timestamp and try again.'          
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_updated_by, v_metadata);
      RETURN v_response;
    ELSE
      -- Record does not exist
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        '00002',
        'No records were found matching the query.',
        'Check the query parameters or ensure data exists.',
        'The requested resource does not exist in the database.'          
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_updated_by, v_metadata);
    END IF;
 END IF;    

  RETURN v_response;

  -- ------------------------------------------------------
  -- Exceptions
  -- ------------------------------------------------------
  
  EXCEPTION
    WHEN OTHERS THEN
      v_response := (
        'ERROR', 
        NULL, 
        NULL, 
        SQLSTATE, 
        'An unexpected error occurred', 
        'Check database logs for more details', 
        SQLERRM
      );
      CALL norpac_commons.i_logs(v_response.status, v_response.message, c_service_name, p_updated_by, v_metadata);
      RETURN v_response;
  
END;
$$ LANGUAGE plpgsql;
