-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.address. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.address CASCADE;

CREATE TABLE norpac_commons.address (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_rt_address_status             UUID             NOT NULL, 
  address_line1                    VARCHAR(128)     NOT NULL, 
  address_line2                    VARCHAR(128)     NULL, 
  locality                         VARCHAR(128)     NOT NULL, 
  admin_area_level1                VARCHAR(128)     NOT NULL, 
  admin_area_level2                VARCHAR(128)     NULL, 
  postal_code                      VARCHAR(20)      NOT NULL, 
  country_code                     CHAR(2)          NULL, 
  latitude                         DECIMAL(9, 6)    NULL, 
  longitude                        DECIMAL(9, 6)    NULL, 
  validated_at                     TIMESTAMP        NULL, 
  validated_by                     VARCHAR(64)      NULL, 
  validation_notes                 TEXT             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.address ADD PRIMARY KEY (id);

CREATE INDEX address_idx01_address
    ON norpac_commons.address(LOWER(address_line1), LOWER(admin_area_level1), LOWER(postal_code));
    
CREATE INDEX address_idx02_address
    ON norpac_commons.address(latitude, longitude, LOWER(address_line1));

ALTER TABLE norpac_commons.address
  ADD CONSTRAINT address_id_rt_address_status
  FOREIGN KEY (id_rt_address_status)
  REFERENCES norpac_commons.rt_values(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.address 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

