-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.address_region. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.address_region CASCADE;

CREATE TABLE norpac_commons.address_region (
  id_address                       UUID             NOT NULL, 
  id_region                        UUID             NOT NULL
);

ALTER TABLE norpac_commons.address_region ADD PRIMARY KEY (id_address, id_region);

ALTER TABLE norpac_commons.address_region
  ADD CONSTRAINT address_region_id_address
  FOREIGN KEY (id_address)
  REFERENCES norpac_commons.address(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.address_region
  ADD CONSTRAINT address_region_id_region
  FOREIGN KEY (id_region)
  REFERENCES norpac_commons.region(id)
  ON DELETE CASCADE;

