-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.billing_interval. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.billing_interval CASCADE;

CREATE TABLE norpac_commons.billing_interval (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_rt_interval_unit              UUID             NOT NULL, 
  name                             VARCHAR(64)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  descritption                     TEXT             NULL, 
  interval_code                    VARCHAR(64)      NOT NULL, 
  interval_value                   INTEGER          NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.billing_interval ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX billing_interval_alt_key
    ON norpac_commons.billing_interval(LOWER(name), id_rt_interval_unit);

ALTER TABLE norpac_commons.billing_interval
  ADD CONSTRAINT billing_interval_id_rt_interval_unit
  FOREIGN KEY (id_rt_interval_unit)
  REFERENCES norpac_commons.rt_values(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.billing_interval 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

