-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.bundle. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.bundle CASCADE;

CREATE TABLE norpac_commons.bundle (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  id_rt_bundle_strategy            UUID             NOT NULL, 
  discount_percent                 DECIMAL(5, 2)    NULL, 
  metadata                         TEXT             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.bundle ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX bundle_alt_key
    ON norpac_commons.bundle(id_rt_bundle_strategy, id_tenant);

ALTER TABLE norpac_commons.bundle
  ADD CONSTRAINT bundle_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES norpac_commons.tenant(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.bundle 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.bundle ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.bundle
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
