-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.bundle_item. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.bundle_item CASCADE;

CREATE TABLE norpac_commons.bundle_item (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_bundle                        UUID             NOT NULL, 
  id_child_product                 UUID             NOT NULL, 
  sequence                         INTEGER          NOT NULL, 
  quantity                         INTEGER          NOT NULL, 
  optional                         BOOLEAN          NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.bundle_item ADD PRIMARY KEY (id);


ALTER TABLE norpac_commons.bundle_item
  ADD CONSTRAINT bundle_item_id_bundle
  FOREIGN KEY (id_bundle)
  REFERENCES norpac_commons.bundle(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.bundle_item
  ADD CONSTRAINT bundle_item_id_child_product
  FOREIGN KEY (id_child_product)
  REFERENCES norpac_commons.product(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.bundle_item 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

