-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.coupon_usage. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.coupon_usage CASCADE;

CREATE TABLE norpac_commons.coupon_usage (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_coupon                        UUID             NOT NULL, 
  id_customer                      UUID             NOT NULL, 
  id_service_order                 UUID             NOT NULL, 
  used_at                          TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.coupon_usage ADD PRIMARY KEY (id);

CREATE INDEX coupon_usage_idx_coupon_usage_coupon
    ON norpac_commons.coupon_usage(id_coupon);
    
CREATE INDEX coupon_usage_idx_coupon_usage_customer
    ON norpac_commons.coupon_usage(id_customer);
    
CREATE INDEX coupon_usage_idx_coupon_usage_order
    ON norpac_commons.coupon_usage(id_service_order);
    
CREATE UNIQUE INDEX coupon_usage_uk_coupon_usage_unique
    ON norpac_commons.coupon_usage(id_coupon, id_customer, id_service_order);

ALTER TABLE norpac_commons.coupon_usage
  ADD CONSTRAINT coupon_usage_id_coupon
  FOREIGN KEY (id_coupon)
  REFERENCES norpac_commons.coupon(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.coupon_usage
  ADD CONSTRAINT coupon_usage_id_customer
  FOREIGN KEY (id_customer)
  REFERENCES norpac_commons.customer(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.coupon_usage
  ADD CONSTRAINT coupon_usage_id_service_order
  FOREIGN KEY (id_service_order)
  REFERENCES norpac_commons.service_order(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.coupon_usage 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

