-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.coupon_product. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.coupon_product CASCADE;

CREATE TABLE norpac_commons.coupon_product (
  id_coupon                        UUID             NOT NULL, 
  id_product                       UUID             NOT NULL
);

ALTER TABLE norpac_commons.coupon_product ADD PRIMARY KEY (id_coupon, id_product);

ALTER TABLE norpac_commons.coupon_product
  ADD CONSTRAINT coupon_product_id_coupon
  FOREIGN KEY (id_coupon)
  REFERENCES norpac_commons.coupon(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.coupon_product
  ADD CONSTRAINT coupon_product_id_product
  FOREIGN KEY (id_product)
  REFERENCES norpac_commons.product(id)
  ON DELETE CASCADE;

