-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.coupon. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.coupon CASCADE;

CREATE TABLE norpac_commons.coupon (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  id_rt_coupon_type                UUID             NOT NULL, 
  name                             VARCHAR(64)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  code                             VARCHAR(64)      NOT NULL, 
  description                      TEXT             NULL, 
  amount                           DECIMAL(10, 2)   NOT NULL, 
  max_uses                         INTEGER          NULL, 
  max_uses_per_customer            INTEGER          NOT NULL, 
  valid_from                       TIMESTAMP        NULL, 
  valid_to                         TIMESTAMP        NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.coupon ADD PRIMARY KEY (id);

CREATE INDEX coupon_idx_coupon_active_dates
    ON norpac_commons.coupon(valid_from, valid_to);
    
CREATE INDEX coupon_idx_coupon_tenant
    ON norpac_commons.coupon(id_tenant);

ALTER TABLE norpac_commons.coupon
  ADD CONSTRAINT coupon_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES norpac_commons.tenant(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.coupon
  ADD CONSTRAINT coupon_id_rt_coupon_type
  FOREIGN KEY (id_rt_coupon_type)
  REFERENCES norpac_commons.rt_values(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.coupon 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.coupon ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.coupon
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
