-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.customer_phone. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.customer_phone CASCADE;

CREATE TABLE norpac_commons.customer_phone (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_customer                      UUID             NOT NULL, 
  id_rt_phone_type                 UUID             NOT NULL, 
  number                           VARCHAR(16)      NOT NULL, 
  extension                        VARCHAR(10)      NULL, 
  is_primary                       BOOLEAN          NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.customer_phone ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX customer_phone_alt_key
    ON norpac_commons.customer_phone(id_customer, LOWER(number), LOWER(extension));

ALTER TABLE norpac_commons.customer_phone
  ADD CONSTRAINT customer_phone_id_customer
  FOREIGN KEY (id_customer)
  REFERENCES norpac_commons.customer(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.customer_phone
  ADD CONSTRAINT customer_phone_id_rt_phone_type
  FOREIGN KEY (id_rt_phone_type)
  REFERENCES norpac_commons.rt_values(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.customer_phone 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

