-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.customer. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.customer CASCADE;

CREATE TABLE norpac_commons.customer (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  customer_id                      VARCHAR(32)      NULL, 
  business_name                    VARCHAR(64)      NULL, 
  first_name                       VARCHAR(64)      NOT NULL, 
  last_name                        VARCHAR(64)      NOT NULL, 
  email                            VARCHAR(255)     NULL        CHECK (email ~ '^[A-Za-z0-9]+([._%+-][A-Za-z0-9]+)*@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'), 
  phone_number                     VARCHAR(16)      NULL, 
  preferred_contact                VARCHAR(64)      NULL, 
  date_of_birth                    DATE             NULL, 
  description                      TEXT             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.customer ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX customer_alt_key
    ON norpac_commons.customer(LOWER(customer_id), id_tenant);
    
CREATE UNIQUE INDEX customer_customer_idx01
    ON norpac_commons.customer(LOWER(email), id_tenant);

ALTER TABLE norpac_commons.customer
  ADD CONSTRAINT customer_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES norpac_commons.tenant(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.customer 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.customer ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.customer
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
