-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.feature. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.feature CASCADE;

CREATE TABLE norpac_commons.feature (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  name                             VARCHAR(64)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  description                      TEXT             NULL, 
  is_addon                         BOOLEAN          NULL        DEFAULT FALSE, 
  metadata                         JSON             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.feature ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX feature_alt_key
    ON norpac_commons.feature(id_tenant, LOWER(name));

ALTER TABLE norpac_commons.feature
  ADD CONSTRAINT feature_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES norpac_commons.tenant(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.feature 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.feature ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.feature
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
