-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.pricing_tier. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.pricing_tier CASCADE;

CREATE TABLE norpac_commons.pricing_tier (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_pricing                       UUID             NOT NULL, 
  min_quantity                     INTEGER          NOT NULL, 
  max_quantity                     INTEGER          NULL, 
  price_per_unit                   DECIMAL(10, 2)   NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.pricing_tier ADD PRIMARY KEY (id);


ALTER TABLE norpac_commons.pricing_tier
  ADD CONSTRAINT pricing_tier_id_pricing
  FOREIGN KEY (id_pricing)
  REFERENCES norpac_commons.pricing(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.pricing_tier 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

