-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.pricing. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.pricing CASCADE;

CREATE TABLE norpac_commons.pricing (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_product                       UUID             NOT NULL, 
  id_rt_pricing_type               UUID             NOT NULL, 
  id_rt_billing_period             UUID             NOT NULL, 
  id_rt_currency_code              UUID             NOT NULL, 
  amount                           DECIMAL(10, 2)   NOT NULL, 
  rate_per_unit                    DECIMAL(10, 2)   NULL, 
  minimum_charge                   DECIMAL(10, 2)   NULL, 
  valid_from                       DATE             NOT NULL, 
  valid_to                         DATE             NULL, 
  metadata                         TEXT             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.pricing ADD PRIMARY KEY (id);


ALTER TABLE norpac_commons.pricing
  ADD CONSTRAINT pricing_id_product
  FOREIGN KEY (id_product)
  REFERENCES norpac_commons.product(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.pricing 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

