-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.pricing_schedule_mapping. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.pricing_schedule_mapping CASCADE;

CREATE TABLE norpac_commons.pricing_schedule_mapping (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_pricing                       UUID             NOT NULL, 
  id_schedule_rule                 UUID             NOT NULL, 
  effective_date                   DATE             NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.pricing_schedule_mapping ADD PRIMARY KEY (id);


ALTER TABLE norpac_commons.pricing_schedule_mapping
  ADD CONSTRAINT pricing_schedule_mapping_id_pricing
  FOREIGN KEY (id_pricing)
  REFERENCES norpac_commons.pricing(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.pricing_schedule_mapping
  ADD CONSTRAINT pricing_schedule_mapping_id_schedule_rule
  FOREIGN KEY (id_schedule_rule)
  REFERENCES norpac_commons.schedule_rule(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.pricing_schedule_mapping 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

