-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.product_feature_mapping. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.product_feature_mapping CASCADE;

CREATE TABLE norpac_commons.product_feature_mapping (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_product                       UUID             NOT NULL, 
  id_feature                       UUID             NOT NULL, 
  included                         BOOLEAN          NOT NULL, 
  addon_price                      DECIMAL(10, 2)   NULL        DEFAULT 0.00, 
  metadata                         JSON             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.product_feature_mapping ADD PRIMARY KEY (id);


ALTER TABLE norpac_commons.product_feature_mapping
  ADD CONSTRAINT product_feature_mapping_id_product
  FOREIGN KEY (id_product)
  REFERENCES norpac_commons.product(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.product_feature_mapping
  ADD CONSTRAINT product_feature_mapping_id_feature
  FOREIGN KEY (id_feature)
  REFERENCES norpac_commons.feature(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.product_feature_mapping 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

