-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.product_service_details. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.product_service_details CASCADE;

CREATE TABLE norpac_commons.product_service_details (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_product                       UUID             NOT NULL, 
  estimated_duration_minutes       INTEGER          NOT NULL, 
  requires_pressure_wash           BOOLEAN          NOT NULL, 
  equipment_type                   VARCHAR(64)      NULL, 
  metadata                         TEXT             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.product_service_details ADD PRIMARY KEY (id);


ALTER TABLE norpac_commons.product_service_details
  ADD CONSTRAINT product_service_details_id_product
  FOREIGN KEY (id_product)
  REFERENCES norpac_commons.product(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.product_service_details 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

