-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.product. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.product CASCADE;

CREATE TABLE norpac_commons.product (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  id_rt_product_type               UUID             NOT NULL, 
  id_rt_product_status             UUID             NOT NULL, 
  id_rt_product_category           UUID             NOT NULL, 
  name                             VARCHAR(64)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  code                             VARCHAR(64)      NOT NULL, 
  description                      TEXT             NULL, 
  metadata                         JSON             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.product ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX product_alt_key
    ON norpac_commons.product(LOWER(code), id_tenant);

ALTER TABLE norpac_commons.product
  ADD CONSTRAINT product_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES norpac_commons.tenant(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.product
  ADD CONSTRAINT product_id_rt_product_type
  FOREIGN KEY (id_rt_product_type)
  REFERENCES norpac_commons.rt_values(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.product
  ADD CONSTRAINT product_id_rt_product_status
  FOREIGN KEY (id_rt_product_status)
  REFERENCES norpac_commons.rt_values(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.product
  ADD CONSTRAINT product_id_rt_product_category
  FOREIGN KEY (id_rt_product_category)
  REFERENCES norpac_commons.rt_values(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.product 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.product ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.product
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
