-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.product_category. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.product_category CASCADE;

CREATE TABLE norpac_commons.product_category (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  id_parent_category               UUID             NULL, 
  code                             VARCHAR(64)      NOT NULL, 
  name                             VARCHAR(64)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  description                      TEXT             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.product_category ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX product_category_code
    ON norpac_commons.product_category(LOWER(code));

ALTER TABLE norpac_commons.product_category
  ADD CONSTRAINT product_category_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES norpac_commons.tenant(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.product_category
  ADD CONSTRAINT product_category_id_parent_category
  FOREIGN KEY (id_parent_category)
  REFERENCES norpac_commons.product_category(id)
  ON DELETE SET NULL;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.product_category 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.product_category ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.product_category
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
