-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.region_postal_code. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.region_postal_code CASCADE;

CREATE TABLE norpac_commons.region_postal_code (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  id_region                        UUID             NOT NULL, 
  postal_code                      VARCHAR(20)      NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.region_postal_code ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX region_postal_code_alt_key
    ON norpac_commons.region_postal_code(id_tenant, id_region, LOWER(postal_code));

ALTER TABLE norpac_commons.region_postal_code
  ADD CONSTRAINT region_postal_code_id_region
  FOREIGN KEY (id_region)
  REFERENCES norpac_commons.region(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.region_postal_code 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.region_postal_code ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.region_postal_code
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
