-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.region_polygon. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.region_polygon CASCADE;

CREATE TABLE norpac_commons.region_polygon (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  id_region                        UUID             NOT NULL, 
  sequence                         INTEGER          NOT NULL, 
  latitude                         DECIMAL(9, 6)    NOT NULL, 
  longitude                        DECIMAL(9, 6)    NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.region_polygon ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX region_polygon_alt_key
    ON norpac_commons.region_polygon(id_tenant, id_region, latitude, longitude);

ALTER TABLE norpac_commons.region_polygon
  ADD CONSTRAINT region_polygon_id_region
  FOREIGN KEY (id_region)
  REFERENCES norpac_commons.region(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.region_polygon 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.region_polygon ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.region_polygon
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
