-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.rt_values. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.rt_values CASCADE;

CREATE TABLE norpac_commons.rt_values (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  id_rt_type                       UUID             NOT NULL, 
  sequence                         INTEGER          NOT NULL, 
  name                             VARCHAR(64)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  description                      TEXT             NULL, 
  value                            VARCHAR(255)     NOT NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.rt_values ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX rt_values_alt_key
    ON norpac_commons.rt_values(id_tenant, id_rt_type, LOWER(name));

ALTER TABLE norpac_commons.rt_values
  ADD CONSTRAINT rt_values_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES norpac_commons.tenant(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.rt_values
  ADD CONSTRAINT rt_values_id_rt_type
  FOREIGN KEY (id_rt_type)
  REFERENCES norpac_commons.rt_type(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.rt_values 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.rt_values ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.rt_values
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
