-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.service_order. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.service_order CASCADE;

CREATE TABLE norpac_commons.service_order (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_tenant                        UUID             NOT NULL, 
  id_customer                      UUID             NOT NULL, 
  id_invoice                       UUID             NOT NULL, 
  id_product                       UUID             NOT NULL, 
  id_subscription_plan             UUID             NULL, 
  id_schedule_rule                 UUID             NULL, 
  id_rt_service_status             UUID             NOT NULL, 
  service_date                     DATE             NOT NULL, 
  metadata                         TEXT             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.service_order ADD PRIMARY KEY (id);


ALTER TABLE norpac_commons.service_order
  ADD CONSTRAINT service_order_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES norpac_commons.tenant(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.service_order
  ADD CONSTRAINT service_order_id_product
  FOREIGN KEY (id_product)
  REFERENCES norpac_commons.product(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.service_order
  ADD CONSTRAINT service_order_id_rt_service_status
  FOREIGN KEY (id_rt_service_status)
  REFERENCES norpac_commons.rt_values(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.service_order 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

ALTER TABLE norpac_commons.service_order ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.service_order
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
