-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.subscription_plan. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.subscription_plan CASCADE;

CREATE TABLE norpac_commons.subscription_plan (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  id_product                       UUID             NOT NULL, 
  id_rt_billing_frequency          UUID             NOT NULL, 
  id_rt_currency_code              UUID             NOT NULL, 
  id_rt_renewal_policy             UUID             NOT NULL, 
  plan_name                        VARCHAR(64)      NOT NULL, 
  base_price                       DECIMAL(10, 2)   NOT NULL, 
  trial_period_days                INTEGER          NULL        DEFAULT 0, 
  recurrence_rule                  TEXT             NULL, 
  metadata                         JSON             NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.subscription_plan ADD PRIMARY KEY (id);


ALTER TABLE norpac_commons.subscription_plan
  ADD CONSTRAINT subscription_plan_id_product
  FOREIGN KEY (id_product)
  REFERENCES norpac_commons.product(id)
  ON DELETE CASCADE;

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.subscription_plan 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

