-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.tenant. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.tenant CASCADE;

CREATE TABLE norpac_commons.tenant (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  name                             VARCHAR(64)      NOT NULL    CHECK (name ~ '^[A-Za-z0-9_][A-Za-z0-9\s\-,\.&''()*_:]{0,30}[A-Za-z0-9_]$'), 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.tenant ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX tenant_alt_key
    ON norpac_commons.tenant(LOWER(name));

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.tenant 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

