-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.tenant_user. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.tenant_user CASCADE;

CREATE TABLE norpac_commons.tenant_user (
  id_tenant                        UUID             NOT NULL, 
  id_user                          UUID             NOT NULL
);

ALTER TABLE norpac_commons.tenant_user ADD PRIMARY KEY (id_tenant, id_user);

ALTER TABLE norpac_commons.tenant_user
  ADD CONSTRAINT tenant_user_id_tenant
  FOREIGN KEY (id_tenant)
  REFERENCES norpac_commons.tenant(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.tenant_user
  ADD CONSTRAINT tenant_user_id_user
  FOREIGN KEY (id_user)
  REFERENCES norpac_commons.user(id)
  ON DELETE CASCADE;

ALTER TABLE norpac_commons.tenant_user ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON norpac_commons.tenant_user
  FOR ALL TO web_update
    USING (id_tenant = current_setting('app.current_tenant')::uuid);
