-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.user. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.user CASCADE;

CREATE TABLE norpac_commons.user (
  id                               UUID             NOT NULL    DEFAULT GEN_RANDOM_UUID(), 
  email                            VARCHAR(255)     NOT NULL    CHECK (email ~ '^[A-Za-z0-9]+([._%+-][A-Za-z0-9]+)*@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'), 
  last_name                        VARCHAR(64)      NULL, 
  first_name                       VARCHAR(64)      NULL, 
  created_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  created_by                       VARCHAR(32)      NOT NULL, 
  updated_at                       TIMESTAMP        NOT NULL    DEFAULT CURRENT_TIMESTAMP, 
  updated_by                       VARCHAR(32)      NOT NULL, 
  is_active                        BOOLEAN          NOT NULL    DEFAULT TRUE
);

ALTER TABLE norpac_commons.user ADD PRIMARY KEY (id);

CREATE UNIQUE INDEX user_alt_key
    ON norpac_commons.user(LOWER(email));

CREATE TRIGGER update_at
  BEFORE UPDATE ON norpac_commons.user 
    FOR EACH ROW
      EXECUTE FUNCTION update_at();

