-- ---------------------------------------------------------------------------------------
-- Table: norpac_commons.user_role. Generated by Pareto Factory™ "Be Consistent"
-- ---------------------------------------------------------------------------------------
DROP TABLE IF EXISTS norpac_commons.user_role CASCADE;

CREATE TABLE norpac_commons.user_role (
  id_user                          UUID             NOT NULL, 
  id_role                          UUID             NOT NULL
);

ALTER TABLE norpac_commons.user_role ADD PRIMARY KEY (id_user, id_role);

ALTER TABLE norpac_commons.user_role
  ADD CONSTRAINT user_role_id_user
  FOREIGN KEY (id_user)
  REFERENCES norpac_commons.user(id)
  ON DELETE CASCADE;
    
ALTER TABLE norpac_commons.user_role
  ADD CONSTRAINT user_role_id_role
  FOREIGN KEY (id_role)
  REFERENCES norpac_commons.role(id)
  ON DELETE CASCADE;

